In [1]:
from torchvision.ops import RoIAlign
import torch
import numpy as np
import cv2


In [2]:

img = cv2.imread(r'C:\Users\wmh_w\Pictures\Camera Roll\34.jpg')
img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
h,w,_ = img.shape


In [3]:
img = np.transpose(img,axes=(2,0,1))
img2 = cv2.imread(r'C:\Users\wmh_w\Pictures\Camera Roll\1082867.jpg')


In [4]:
img2 = cv2.resize(img2,(w,h))


In [5]:
img2.shape

(425, 640, 3)

In [6]:
img2 = cv2.cvtColor(img2,cv2.COLOR_BGR2RGB)
img2 = np.transpose(img2,axes=(2,0,1))
imgs = np.stack((img,img2),axis=0)
imgss = torch.from_numpy(imgs)
boxes = [torch.tensor([[200,200,400,400],[100,300,400,400]]),torch.tensor([[200,200,400,400],[100,300,400,400]])]
boxes = [box.float() for box in boxes]
imgss=imgss.float()

In [14]:
roi_fn = RoIAlign((50,50),sampling_ratio=2,spatial_scale=1.0)

In [25]:
outs = roi_fn(imgss,boxes)

In [26]:
outs.shape

torch.Size([4, 3, 50, 50])

In [27]:
fmap1 = outs[0]

In [28]:
fmap1_img = np.array(fmap1,dtype=np.uint8)

In [29]:
fmap1_img = fmap1_img.transpose((1,2,0))

In [30]:
fmap1_img.shape

(50, 50, 3)

In [31]:
cv2.imshow("fmap1",fmap1_img)
cv2.waitKey(0)

-1

In [32]:
for i in range(len(outs)):
    fmap1 = outs[i]
    fmap1_img = np.array(fmap1,dtype=np.uint8)
    fmap1_img = fmap1_img.transpose((1,2,0))
    cv2.imshow(f"fmap{i}",fmap1_img)
cv2.waitKey(0)

In [3]:
import torch
a = torch.randn(3,4,5)
b = torch.sum(a,dim=-1,dtype=torch.bool)

In [4]:
b

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [5]:
c = torch.zeros_like(a,dtype=bool)

In [9]:
c[2] = 1.0

In [10]:
c

tensor([[[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]]])

In [11]:
a = torch.rand(3,4)
b = a[:,2]
c = a[:,3]

In [12]:
b.shape

torch.Size([3])

In [13]:
d = torch.cat([b,c],dim=0)

In [14]:
d

tensor([0.3563, 0.7507, 0.4982, 0.1527, 0.5630, 0.0707])

In [15]:
b

tensor([0.3563, 0.7507, 0.4982])

In [16]:
c

tensor([0.1527, 0.5630, 0.0707])

In [1]:
import numpy as np

In [9]:
a = np.arange(10)

In [10]:
b = np.arange(9,-1,-1)

In [11]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [13]:
c = np.repeat(a,b)

In [14]:
c.shape

(45,)

In [15]:
c

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7,
       8])

In [16]:
a = torch.rand(10,4)
mask = torch.randn(10)>0

In [17]:
a

tensor([[0.4648, 0.8488, 0.7956, 0.3733],
        [0.1984, 0.5070, 0.6885, 0.5095],
        [0.9397, 0.4925, 0.8578, 0.8870],
        [0.0963, 0.9066, 0.8277, 0.4644],
        [0.8788, 0.3658, 0.5461, 0.1853],
        [0.9210, 0.7531, 0.2643, 0.7398],
        [0.2864, 0.3499, 0.7489, 0.3944],
        [0.9341, 0.0360, 0.8360, 0.1009],
        [0.7450, 0.6598, 0.9424, 0.4230],
        [0.6460, 0.7246, 0.3504, 0.7495]])

In [19]:
mask

tensor([False,  True,  True,  True, False, False,  True, False,  True, False])

In [20]:
b= a[mask,:]

In [21]:
b

tensor([[0.1984, 0.5070, 0.6885, 0.5095],
        [0.9397, 0.4925, 0.8578, 0.8870],
        [0.0963, 0.9066, 0.8277, 0.4644],
        [0.2864, 0.3499, 0.7489, 0.3944],
        [0.7450, 0.6598, 0.9424, 0.4230]])

In [29]:
a = [torch.ones(2,4),torch.randn(3,4),torch.zeros(1,4),torch.ones(1,4)]
mk = [torch.sum(boxes)>0 for boxes in a]

In [30]:
mk

[tensor(True), tensor(True), tensor(False), tensor(True)]

In [31]:
m_k = np.array(mk)

In [32]:
m_k

array([ True,  True, False,  True])

In [33]:
m_k.repeat([1,2,3,4],axis=0)

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True])

In [34]:
a = torch.rand(4,5,5)

In [35]:
b = a[m_k]

In [37]:
b.shape

torch.Size([3, 5, 5])

In [1]:
from torchvision.ops import RoIAlign
import torch

In [2]:
net = RoIAlign(14,8,2.0)

In [3]:
type(net)

torchvision.ops.roi_align.RoIAlign

In [56]:
for i in net.parameters():
    print(i.shape)


In [4]:
net2 = torch.nn.Upsample(50,2)

In [24]:
type(net2)==torch.nn.Upsample

True

In [11]:
for i in net2.parameters():
    print(i)

In [13]:
net3 = torch.nn.Conv2d(3,10,3,1,1)

In [19]:
for p in net3.parameters():
    print(type(p))

<class 'torch.nn.parameter.Parameter'>
<class 'torch.nn.parameter.Parameter'>


In [29]:
for p in net3.modules():
    print(type(p))
    print(p.__class__.__name__)
    print(type(p)==torch.nn.Conv2d)
    for i in p.parameters():
        print(i.shape)

<class 'torch.nn.modules.conv.Conv2d'>
Conv2d
True
torch.Size([10, 3, 3, 3])
torch.Size([10])


In [30]:
net4 = torch.nn.BatchNorm2d(10)

In [31]:
type(net4)

torch.nn.modules.batchnorm.BatchNorm2d

In [54]:
for p in net4.modules():
    print(type(p))
    print(p.__class__.__name__)
    print(p.__class__ == type(p))
    print(p.weight.shape)
    print(p.bias.shape)


<class 'torch.nn.modules.batchnorm.BatchNorm2d'>
BatchNorm2d
True
torch.Size([10])
torch.Size([10])


In [51]:
net5 = torch.nn.Sequential(torch.nn.Conv2d(3,10,3,2,1),torch.nn.Upsample(10),torch.nn.ReLU())

In [52]:
for m in net5.modules():
    classname = m.__class__.__name__
    if classname == "Conv2d":
        print(type(m))

<class 'torch.nn.modules.conv.Conv2d'>


In [57]:
d = {"a":34,"b":567,67:"faad"}

In [61]:
for k , v in d.items():
    print(k)
    print(type(k))
    print(v)
    print(type(v))

a
<class 'str'>
34
<class 'int'>
b
<class 'str'>
567
<class 'int'>
67
<class 'int'>
faad
<class 'str'>


In [3]:
a = map(int,["21","43","908"])

In [5]:
list(a)

[21, 43, 908]

In [8]:
import numpy as np
a = np.arange(10)

In [9]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a.shape

(10,)

In [12]:
b = a.reshape(-1,1)

In [14]:
id(a)

139677751184528

In [15]:
id(b)

139677750644048

In [1]:
import numpy as np

In [3]:
a = np.random.rand(10,5)

In [4]:
a

array([[0.25943636, 0.20461415, 0.10878654, 0.452907  , 0.57474684],
       [0.31371256, 0.69981241, 0.99619057, 0.45920574, 0.02742743],
       [0.9385776 , 0.14052751, 0.5278124 , 0.73537252, 0.98091792],
       [0.64968268, 0.33993764, 0.01625614, 0.48441071, 0.51423357],
       [0.06749972, 0.2124686 , 0.03204137, 0.342146  , 0.44514122],
       [0.50050143, 0.71111742, 0.69629824, 0.47593523, 0.63757962],
       [0.8135753 , 0.04672343, 0.13873541, 0.29149244, 0.67320108],
       [0.21737602, 0.12946946, 0.78751623, 0.05115643, 0.18293225],
       [0.85211635, 0.77598467, 0.44949858, 0.6265546 , 0.2157016 ],
       [0.81436685, 0.02972481, 0.91237117, 0.02730474, 0.31825957]])

In [9]:
m  = a[:,2]>0.5

In [10]:
m

array([False,  True,  True, False, False,  True, False,  True, False,
        True])

In [11]:
mk = a[:,3] > 0.3

In [12]:
mk

array([ True,  True,  True,  True,  True,  True, False, False,  True,
       False])

In [14]:
mask = m*mk

In [15]:
mask

array([False,  True,  True, False, False,  True, False, False, False,
       False])